from dataclasses import dataclass
from enum import Enum


class IngestionErrorCode(str, Enum):
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    UNSUPPORTED_FILE_TYPE = "UNSUPPORTED_FILE_TYPE"
    FILE_PARSE_FAILED = "FILE_PARSE_FAILED"
    EMPTY_DOCUMENT = "EMPTY_DOCUMENT"
    LOW_QUALITY_EXTRACTION = "LOW_QUALITY_EXTRACTION"
    NORMALIZATION_FAILED = "NORMALIZATION_FAILED"
    CHUNKING_FAILED = "CHUNKING_FAILED"
    OPENAI_AUTH_ERROR = "OPENAI_AUTH_ERROR"
    OPENAI_RATE_LIMIT = "OPENAI_RATE_LIMIT"
    OPENAI_TIMEOUT = "OPENAI_TIMEOUT"
    OPENAI_TRANSIENT_ERROR = "OPENAI_TRANSIENT_ERROR"
    OPENAI_INVALID_REQUEST = "OPENAI_INVALID_REQUEST"
    OPENAI_RESPONSE_EMPTY = "OPENAI_RESPONSE_EMPTY"
    OPENAI_EMBEDDING_FAILED = "OPENAI_EMBEDDING_FAILED"
    OPENAI_CHAT_FAILED = "OPENAI_CHAT_FAILED"
    EMBEDDING_API_FAILED = "EMBEDDING_API_FAILED"
    VECTOR_PERSIST_FAILED = "VECTOR_PERSIST_FAILED"
    DB_WRITE_FAILED = "DB_WRITE_FAILED"
    OBJECT_STORAGE_FAILED = "OBJECT_STORAGE_FAILED"
    TRANSIENT_EXTERNAL_ERROR = "TRANSIENT_EXTERNAL_ERROR"


@dataclass(slots=True)
class IngestionError(Exception):
    code: IngestionErrorCode
    message: str
    retryable: bool = False
    details: dict | None = None

    def __str__(self) -> str:
        return self.message
